### ISSUE TITLE
Additional debug messages for Event Hubs configuration

### ISSUE THREAD

**Issue by richardjharding** [shanepeckham/captureorderack#4]
We burned a lot of time during the challenge trying to work out what we had mis-configured  - it wasn't clear from the container logs whether we had successfully sent the message to Even Hubs - turned out we had used the wrong event hub key - would be useful if more errors were captured and logged in that scenario - also a little more guidance on the need for Event Hub partition key

(was an excellent 2 days though!)

**Comment by shanepeckham** [comment]
Thank you Richard,

Both your points were addressed this morning, thank you so much for the feedback and attending!

Shane
